CREATE TABLE CUSTOMER (ID NUMBER(19) NOT NULL, EMAIL VARCHAR2(255) NULL, PASSWORD VARCHAR2(255) NULL, PRIMARY KEY (ID))
CREATE TABLE ITEM (ID NUMBER(19) NOT NULL, DESCRIPTION VARCHAR2(255) NULL, FOTO BLOB NULL, PRICE NUMBER(19,4) NULL, SOLD BLOB NULL, TITLE VARCHAR2(255) NULL, BUYER_ID NUMBER(19) NULL, SELLER_ID NUMBER(19) NULL, PRIMARY KEY (ID))
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_BUYER_ID FOREIGN KEY (BUYER_ID) REFERENCES CUSTOMER (ID)
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_SELLER_ID FOREIGN KEY (SELLER_ID) REFERENCES CUSTOMER (ID)
